# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rack-contrib/all/rack-contrib.rbi
#
# rack-contrib-2.3.0

module Rack
end
module Rack::Contrib
  def self.release; end
end
