query GetMentions {
    yourfeed {
        mentions {
            twt {
                createdAt hash content replyTo
                mentions {
                    feed {
                        url nick
                    }
                }
                feed {
                    url nick avatar
                 }
            }
        }
    }
}

# that should be enough to construct a basic list of notifications for any feed
# yourfeed - feed(url: ${feed})
